### ISSUE TITLE
Example has 'magento-data-1' hardcoded

### ISSUE THREAD

**Issue by peterjaap** [kojiromike/docker-magento#5]
In the example where to mount a volume, it says;
```mkdir -p <mountpoint> && mount_smbfs -N //guest@<docker host ip>/magento_data_1 <mountpoint>```

It has 'magento_data_1' in the line, which leads me to believe that the directory you were working in was called 'magento' and Fig has used that as a prefix to '_data_1'. This might differ for other users.

**Comment by kojiromike** [comment]
Thanks again!
