### ISSUE TITLE
Documentation...

### ISSUE THREAD

**Issue by tabr0201** [kojiromike/docker-magento#7]
I am new to docker, and have setup multiple projects. I got the app stack running and see the basic html file that shows me it works.

However, I have not been able to follow to magento tools documentation to get everything up and working. Could be just me, but maybe check through and let me know if you update this documentation at all. I'd like to try again as this is a great project!

**Comment by kojiromike** [comment]
Hi, thanks for the feedback. Could you describe where you got stuck in the magento-tools documentation? It would help me focus my efforts.

**Comment by kojiromike** [comment]
Since there has been no action on this issue in quite a while I'm going to close it. Please feel free to open a new one if you have more trouble.
