### ISSUE TITLE
followed the tl;dr and got an error

### ISSUE THREAD

**Issue by javaknight** [kojiromike/docker-magento#9]
Environment is ubuntu 14 lts

Cannot start container 3fd93bcca858ad03a1c33a196efea29575fa84fa24a40058284ee5e3e7644919: [8] System error: exec: "/usr/sbin/php5-fpm": stat /usr/sbin/php5-fpm: no such file or directory

**Comment by kojiromike** [comment]
I think this is handled by #8. I plan to merge that in soon, just need a little time.

**Comment by javaknight** [comment]
Still getting the same error when I update the file.

**Comment by kojiromike** [comment]
You would have needed to rebuild the container. Try doing a `docker pull kojiromike/magento_php` now, and see if it's fixed.

**Comment by javaknight** [comment]
Hello. I'm new to docker... I am able to get the container running, but I am unable to actually connect to it. I tried using -P option to expose those ports, but I am unable to connect to them. Any idea what I am doing wrong?

Apologies for the formatting.
Environment is out of the box Ubuntu (Canonical) from the EC2 default images.

ubuntu@xxx:~/tmp$ docker --version
Docker version 1.6.0, build 4749651
ubuntu@xx:~/tmp$ sudo docker run -P -d kojiromike/magento_php:latest
9fe064335045f279a019927bd5154070964b4e8aa0c01004a10d530334a8d59d
ubuntu@xxx:~/tmp$ sudo docker ps
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                              NAMES
9fe064335045        kojiromike/magento_php:latest   "/usr/local/sbin/php   12 seconds ago      Up 11 seconds       0.0.0.0:32771->9000/tcp, 0.0.0.0:32770->9001/tcp   naughty_wozniak

ubuntu@XXX:~/tmp$ sudo docker inspect naughty_wozniak|grep IP
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.7",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "fe80::42:acff:fe11:7",
        "LinkLocalIPv6PrefixLen": 64,

ubuntu@ip-xxx:~/tmp$ wget 172.17.0.7:9000
--2015-05-01 14:27:23--  http://172.17.0.7:9000/
Connecting to 172.17.0.7:9000... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2015-05-01 14:27:24--  (try: 2)  http://172.17.0.7:9000/
Connecting to 172.17.0.7:9000... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

**Comment by kojiromike** [comment]
I hope you don't mind I updated your comment with markdown formatting.

The php image is an fpm container, not an http server itself. It needs to be hooked up to a web server container to work correctly. That said, if you want to connect to it directly you need to talk to it on the exposed port. You can see that in your above output here:

```
ubuntu@xxx:~/tmp$ sudo docker ps
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS                                              NAMES
9fe064335045        kojiromike/magento_php:latest   "/usr/local/sbin/php   12 seconds ago      Up 11 seconds       0.0.0.0:32771->9000/tcp, 0.0.0.0:32770->9001/tcp   naughty_wozniak
```

Port 9000 is exposed on 32771 and port 9001 on 32770. Another way to see that is with the `docker port` command.

**Comment by kojiromike** [comment]
Since there has been no motion on this issue in quite a while I'm going to close it. If you still have problems, please feel free to open a new issue.
